# Generated by Django 5.0.6 on 2024-06-15 00:57

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(default=api.models.generate_user_id, primary_key=True, serialize=False, unique=True),
        ),
    ]
