# Generated by Django 5.0.6 on 2024-06-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='grade',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
