# Generated by Django 5.0.6 on 2024-06-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_team_coach_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='coach_first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='team',
            name='coach_last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
