# Generated by Django 5.0.6 on 2024-06-25 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_team_coach_first_name_team_coach_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
