# Generated by Django 5.0.6 on 2024-06-26 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_archivedteams'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchivedTeams',
        ),
    ]
