# Generated by Django 5.0.6 on 2024-06-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_delete_archivedteams'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bats',
            field=models.CharField(default='N/A', max_length=30),
        ),
    ]
