# Generated by Django 5.0.6 on 2024-06-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_player_id_player_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.IntegerField(default=2064, primary_key=True, serialize=False, unique=True),
        ),
    ]
