# Generated by Django 5.0.6 on 2024-06-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_player_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.IntegerField(default=2459, primary_key=True, serialize=False, unique=True),
        ),
    ]
