# Generated by Django 5.0.6 on 2024-06-28 02:05

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_player_number_alter_player_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.IntegerField(default=9742, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='ArchivedTeam',
            fields=[
                ('team_id', models.IntegerField(default=api.models.generate_team_id, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(default='N/A', max_length=10)),
                ('coach_first_name', models.CharField(blank=True, max_length=30)),
                ('coach_last_name', models.CharField(blank=True, max_length=30)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archived_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
