# Generated by Django 5.0.6 on 2024-06-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_team_league_alter_player_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedteam',
            name='league',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.IntegerField(default=8779, primary_key=True, serialize=False, unique=True),
        ),
    ]
