# Generated by Django 5.0.6 on 2024-06-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_archivedteam_league_alter_player_player_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leagues',
            fields=[
                ('league_id', models.IntegerField(default=139401, primary_key=True, serialize=False, unique=True)),
                ('league', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.IntegerField(default=8765, primary_key=True, serialize=False, unique=True),
        ),
    ]
